[entities]

Stade_metastatique_avec_localisations
Histologie_tumorale
Topographie_du_primitif
Stade_OMS_ECOG_Karnofsky
Reponse_a_la_chimiotherapie
ATCD_geriatriques_et_medicaux_significatifs_pour_la_prise_en_charge 
Biomarqueurs_therapeutiques
Evolutivite_en_lien_avec_le_cancer
Symptomes
Signes_physiques
Statut_tabagique
Traitement_specifique_du_cancer

[events]



[relations]



[attributes]