# -*- Mode: Text; tab-width: 8; indent-tabs-mode: nil; coding: utf-8; -*-
# vim:set ft=conf ts=2 sw=2 sts=2 autoindent:

[labels]

# Label definitions for display. The labels are separated by pipe
# characters "|".

# The first label must correspond to the form found first in other
# configuration files. As this form must be valid for use in e.g. the
# BioNLP ST standoff format, it must have only ASCII alphanumerics,
# "_" or "-" (i.e. match '^[a-zA-Z0-9_-]$').

# Labels other than the first define forms that are presented to the
# user in the annotation interface, with the first form being the
# preferred full form and the others abbreviations that will be used
# if fuller forms do not fit in the given space. These have no format
# restrictions and can contain e.g. space (this tends to make the
# first and second columns identical for most terms, which do not
# contain space). Surrounding space is ignored.

Stade_metastatique_avec_localisations | Stade métastatique (+localisations)
Histologie_tumorale | Histologie tumorale
Topographie_du_primitif | Topographie du primitif
Stade_OMS_ECOG_Karnofsky | Stade OMS/ECOG/Karnofsky
Reponse_a_la_chimiotherapie | Réponse à la chimiothérapie
ATCD_geriatriques_et_medicaux_significatifs_pour_la_prise_en_charge | ATCD gériatriques et médicaux significatifs pour la prise en charge
Biomarqueurs_therapeutiques | Biomarqueurs thérapeutiques
Evolutivite_en_lien_avec_le_cancer | Evolutivité en lien avec le cancer
Symptomes | Symptômes
Signes_physiques | Signes physiques
Statut_tabagique | Statut tabagique
Traitement_specifique_du_cancer | Traitement spécifique du cancer


[drawing]

# Other aspects of visual presentation. The format is label (form used
# in other configurations, first of the labels) of the annotation
# separated by tab from comma-separated key:value pairs. The recognized
# keys, their values and purpose are:
# - fgColor     : any HTML color specification (e.g. "black"), sets 
#                 the color of a span text in the visualization.
# - bgColor     : any HTML color specification (e.g. "white"), sets 
#                 the color of a span "box" background in the visualization.
# - borderColor : any HTML color specification (e.g. "black"), sets 
#                 the color of a span "box" border in the visualization.
#                 Also supports special value "darken", which specifies to
#                 use a darker shade of bgColor for the border.
# - color       : any HTML color specification (e.g. "black"), sets 
#                 the color of an arc in the visualization.
# - dashArray   : any valid SVG stroke-dasharray specification using
#                 dashes (instead of commas or space) as separators
#                 (e.g. "3-3"), sets the dash/dot pattern for lines
#                 in the span/arc visualization ("-" works for solid 
#                 line)
# The special labels "SPAN_DEFAULT" and "ARC_DEFAULT" are recognized
# as setting defaults that will be used for types without specific
# settings. It is not necessary to define all aspects of the
# visualization (e.g. just Color can be given): defaults will be
# used for unspecified cases.


SPAN_DEFAULT	fgColor:black, bgColor:lightgreen, borderColor:darken
ARC_DEFAULT	color:black, arrowHead:triangle-5
ATTRIBUTE_DEFAULT	glyph:*

Protein	bgColor:#7fa2ff
Simple_chemical	bgColor:#8fcfff
Complex	bgColor:#8f97ff
Organism	bgColor:#ffccaa

Stade_metastatique_avec_localisations bgColor:#54478c
Histologie_tumorale bgColor:#7fa2ff
Topographie_du_primitif bgColor:#2c699a
Stade_OMS_ECOG_Karnofsky bgColor:#048ba8
Reponse_a_la_chimiotherapie bgColor:#0db39e
ATCD_geriatriques_et_medicaux_significatifs_pour_la_prise_en_charge bgColor:#16db93
Biomarqueurs_therapeutiques bgColor:#83e377
Evolutivite_en_lien_avec_le_cancer bgColor:#b9e769
Symptomes bgColor:#efea5a
Signes_physiques bgColor:#f1c453
Statut_tabagique bgColor:#f29e4c
Traitement_specifique_du_cancer bgColor:#ffccaa




